# Generated by Django 5.0 on 2023-12-26 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_title", models.CharField(max_length=200)),
                ("product_code", models.CharField(max_length=15)),
                ("product_price", models.IntegerField()),
                ("warranty", models.IntegerField(blank=True, default=1, null=True)),
                ("brand", models.CharField(max_length=30)),
                ("product_in_stock", models.BooleanField(default=True)),
                (
                    "product_primary_image",
                    models.ImageField(upload_to="product_primary_images/"),
                ),
                (
                    "product_added_by",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="product_filter.category",
                    ),
                ),
            ],
        ),
    ]
